def foo(x)
  puts x
end
foo()

fooメソッドの呼び出し時に引数を与えていないから、出ない
ArgumentError: wrong number of arguments (0 for 1)→引数なしのときに出るエラー
wrong number of arguments (a for b)
a＝呼び出し側の引数の数
b＝メソッド側の引数の数

---------------------------------------------------------

def bar
  puts n
end
n = 10

bar(n)
上の逆で、ArgumentError: wrong number of arguments (1 for 0)と出る
メソッド側の引数がない

---------------------------------------------------------

n= 10　//以下ブロックでも同じ変数を使用できる
n.times do |i| // この行で新しいスコープ（空間を作る）"ブロックローカル変数"
 puts i + n　//ローカルとブロックローカルなのでエラーが出ない　0~9までを１０に足す計算
end

「times」メソッドは、
変数に「0」から「対象のオブジェクトが持つ数値 - 1」を順に代入しながら「{」から「}」までの処理(又は「do」から「end」までの処理)を実行する。
1回繰り返す毎に1ずつ数値は増加する。

---------------------------------------------------------

10.times do |i|
 n = i
 puts n
end
puts n

ブロック内で定義されているnが初めてこの場所で定義されているので、
ブロック内でしか使えない(puts n endまで)
最後にある　puts nでエラーを吐く
